# Generated by Django 6.0.2 on 2026-02-14 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_alter_exercise_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workout",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="one_workout_per_day"
            ),
        ),
    ]
