# Generated by Django 6.0.2 on 2026-02-14 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_workout_one_workout_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalrecord",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="personalrecord",
            name="pr_type",
            field=models.CharField(
                choices=[
                    ("weight", "Weight PR"),
                    ("reps", "Rep PR"),
                    ("sets", "Set PR"),
                ],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalrecord",
            name="previous_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalrecord",
            name="previous_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="personalrecord",
            name="sets",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
